### ISSUE TITLE
I can't start the Multiprocessing module.

### ISSUE THREAD

**Issue by Vovak1919** [CogitoNTNU/AlphaZero#17]
C:\AZ\AlphaZero-CogitoNTNU>python Multiprocessing.py
Traceback (most recent call last):
File "Multiprocessing.py", line 134, in <module>
train(Config, 3000, 8, 500, 600, Config.name)
File "Multiprocessing.py", line 115, in train
x, y_pol, y_val = multiprocess_function(config, num_processes, num_games_each_process, num_search,
File "Multiprocessing.py", line 44, in multiprocess_function
worker.start()
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
self._popen = self._Popen(self)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
return Popen(process_obj)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__                                                                                          reduction.dump(process_obj, to_child)
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
**TypeError: cannot pickle 'module' object**

![AZ_MP_Err](https://user-images.githubusercontent.com/45577803/107623885-1421ec00-6c6b-11eb-8942-04deba9ad614.jpg)

**Comment by Vovak1919** [comment]
The problem was in the 'config' parameter when creating the process. The good thing is that this is easily solved by simply deleting the parameter in Train.py.
It was:
```
def generate_data(res_dict, config1, num_games_each_process, num_search, num_process, name_weights, seeds):
```
After the correction:
```
def generate_data2(res_dict, num_games_each_process, num_search, num_process, name_weights, seeds):
    from FourInARow import Config as config1
```
